AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Discord

Parameters:
  DiscordPublicKey:
    Type: String
    Default: hoge
  StatemachineArn:
    Type: String
    Default: hoge
  SqsQueueName:
    Type: String
    Default: hoge
  Role:
    Type: String
    Default: hoge

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  InteractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: discord-interaction-function
      CodeUri: interaction/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers:
        - !Ref MyLayer
      # 関数URL有効化
      FunctionUrlConfig:
        AuthType: NONE
      # 環境変数
      Environment:
        Variables:
          DISCORD_PUBLIC_KEY: !Ref DiscordPublicKey
          STATEMACHINE_ARM: !Ref StatemachineArn
          SQS_QUEUE_NAME: !Ref SqsQueueName
      Role: !Ref Role
  
  ServerManageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: discord-server-manager-function
      CodeUri: server-manager/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers:
        - !Ref MyLayer
      Role: !Ref Role

  # サードパーティライブリ
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: discord-lambda-layer
      ContentUri: 'layer/'
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
