openapi: 3.0.0
info:
  title: Discordコマンド一覧
  version: 0.0.0
paths:
  /hello:
    get:
      summary: AWS Lambda確認用コマンド(開発用)
      description: BOT確認用コマンド
      responses:
        '200':
          description: 成功
  /start:
    get:
      summary: サーバー起動コマンド
      description: ec2を起動するコマンド
      responses:
        '200':
          description: 成功
  /stop:
    get:
      summary: サーバー停止コマンド
      description: ec2を停止するコマンド
      responses:
        '200':
          description: 成功
